config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :items
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/school.rb
# app/models/school.rb
class School < ApplicationRecord
    after_create_commit { broadcast_append_to "schools" }
    after_update_commit { broadcast_replace_to "schools" }
    after_destroy_commit { broadcast_remove_to "schools" }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/schools_controller.rb
# app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[show edit update destroy]

  def index
    @schools = School.all
  end

  def show; end

  def new
    @school = School.new
  end

  def edit; end

  def create
    @school = School.new(school_params)
    if @school.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @school, notice: "School was successfully created." }
      end
    else
      render :new
    end
  end

  def update
    if @school.update(school_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @school, notice: "School was successfully updated." }
      end
    else
      render :edit
    end
  end

  def destroy
    @school.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
    end
  end

  private

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<!-- app/views/items/_item.html.erb -->
<%= turbo_frame_tag dom_id(item) do %>
  <p>
    <strong><%= item.name %></strong>
    <%= link_to 'Edit', edit_item_path(item), data: { turbo_frame: dom_id(item) } %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>
<%= turbo_frame_tag dom_id(@item) do %>
  <%= render "form", item: @item %>
<% end %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
 <!-- app/views/items/index.html.erb -->
<h1>Items</h1>

<%= turbo_frame_tag 'items' do %>
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
  <%= link_to 'New Item', new_item_path, data: { turbo_frame: 'items' } %>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboFrameDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, data: { turbo_frame: 'frame_2'}) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<!---then where post render each post has uniqe id 'post' ---->
<%= turbo_frame_tag 'post' do %>    
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>
  <!---here are the edit button with same name  turbo frame post ---->
  <%= link_to 'Edit', edit_post_path(post), data: { turbo_frame: 'post' } %>

<!---- so when user click on the edit button it check the id of turbo frame is match or not 
--->
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%= turbo_frame_tag 'post' do %>
  <%= render "form", post: @post %>
  <%= link_to "Show this post", @post, data: { turbo_frame: 'post_1' } %> |
<% end %>
<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
 
     <!---here we create one turbo frame tag name 'post' --->
      <%= turbo_frame_tag 'post_1' do %>
        <% @posts.each do |post| %>
          <%= render post %>
        <% end %>
        <p>
         </p>
      <% end %>
 
<%= link_to "New post", new_post_path, data: { turbo_frame: 'frame_2' } %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= turbo_frame_tag 'frame_2' do %>
  <%= render "form", post: @post %>
<% end%>
<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag 'post_1' do %>
   <%= render @post %>
 <div>
  <%= link_to "Edit this post ", edit_post_path(@post), data: { turbo_frame: 'post_content' } %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
<% end %>

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<!-- app/views/schools/_school.html.erb -->
<%= turbo_frame_tag dom_id(school) do %>
  <div id="<%= dom_id(school) %>">
    <p>
      <strong>Name:</strong>
      <%= school.name %>
    </p>
    <%= link_to "Show", school %> |
    <%= link_to "Edit", edit_school_path(school), data: { turbo_frame: dom_id(school) } %> |
    <%= link_to "Destroy", school, data: { turbo_method: 'delete',  confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/schools/create.turbo_stream.erb
<!-- app/views/schools/create.turbo_stream.erb -->
<%= turbo_stream.append "schools" do %>
  <%= render @school %>
<% end %>

app/views/schools/destroy.turbo_stream.erb
<!-- app/views/schools/destroy.turbo_stream.erb -->
<%= turbo_stream.remove dom_id(@school) %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<!-- app/views/schools/index.html.erb -->
<h1>Schools</h1>

<%= turbo_frame_tag "schools" do %>
  <%= render @schools %>
<% end %>

<%= link_to "New School", new_school_path, data: { turbo_frame: "school_form" } %>

<%= turbo_frame_tag "school_form" %>

app/views/schools/new.html.erb
<h1>New school</h1>
<%= turbo_frame_tag "school_form" do %>
  <%= render "form", school: @school %>
<% end %>
<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school %>

<div>
  <%= link_to "Edit this school", edit_school_path(@school) %> |
  <%= link_to "Back to schools", schools_path %>

  <%= button_to "Destroy this school", @school, method: :delete %>
</div>

app/views/schools/update.turbo_stream.erb
<!-- app/views/schools/update.turbo_stream.erb -->
<%= turbo_stream.replace dom_id(@school) do %>
  <%= render @school %>
<% end %>